### PR TITLE
Add Range.empty and Node.empty

### LINKED ISSUE #113: Rename Range.emptyRange
https://package.elm-lang.org/help/design-guidelines#module-names-should-not-reappear-in-function-names

### LINKED ISSUE #115: Node.empty function
```elm
empty: a -> Node a
empty a = Node Range.emptyRange a
```
What do you think?

### PR DESCRIPTION
**Pull request by jfmengels**
- Introduces Range.empty (fixes #113)
- Introduces Node.empty (fixes #115)
Can be reviewed commit by commit

### CODE REVIEW

**Comment by MartinSStewart** [comment]
This PR is for the next major release of elm-syntax right? Just making sure were not accidentally adding a breaking change into the current version.

**Comment by jfmengels** [comment]
No, this is for V7, and it only makes for a MINOR version change.
I'll remove Range.emptyRange for V8 though yes.

**Comment by MartinSStewart** [comment]
I think I merged these PRs in the wrong order. This PR wants to be merged into cleanup-processing but I just merged cleanup-processing into master. Should this be merged into master?

**Comment by jfmengels** [comment]
Yes this one should be merged into master (all of them I think, I'll have to check). But I'll take care of merging them, don't worry about that :+1:

**Review by MartinSStewart — APPROVED** [review]
Looks good!

**Comment by jfmengels** [comment]
Pushed to master :+1:

**Pull request closed without merging**
