### PR TITLE
Add changelog for 7.2.0

### PR DESCRIPTION
**Pull request by jfmengels**

### CODE REVIEW

**Comment by MartinSStewart** [comment]
Do you know why the AppVeyor builds are failing in some PRs? It seems to happen only to PRs that are not merging into master.

**Comment by jfmengels** [comment]
There has been a fix for that on `master`, but simply cherry-picking it onto the v7 branch doesn't work.

**Comment by MartinSStewart** [comment]
Strange. I'm guessing it's a problem with the CI and not with the PR though?

**Comment by jfmengels** [comment]
Yes, all my PRs on the v7 have been met with this issue. I'll try again later, but I don't feel like this is blocking us. Also, it looks like Travis does the exact same checks as appveyor, so I'm really unsure as to why we have the two build setups.

**Pull request merged**
